dog/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('dog/', views.alldogs, name='alldogs'),
   path('dog/<int:dog_id>/', views.dog_detail, name="dog_detail"),
   path('', views.alldog_image, name="alldog_image"),
   path('medicalcards/', views.medicalcards, name="medicalcards"),
   path('medicalcards/<int:medicalcard_id>/', views.card_detail, name="card_detail"),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dog/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import User
from django.utils import timezone
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFill
from django.utils.translation import gettext_lazy as _

# Create your models here.

class Dog(models.Model):
    name = models.CharField(max_length=25)
    CHOICES = [('male','Male'), ('female','Female')]
    sex = models.CharField(max_length=6, choices=CHOICES, default='male')

    LOC_CHOICES = [('a_pool','A pool'), ('b_pool','B pool'), ('c_pool','C pool'), ('d_pool','D pool'), ('racing','Racing'), ('out','Out')]
    location = models.CharField(max_length=8, choices=LOC_CHOICES, blank = True)
    leader = models.BooleanField()
    for_breeding = models.BooleanField()
    neutered = models.BooleanField()
    avaible_for_adoption = models.BooleanField()
    trekkhundreg = models.URLField(blank = True)
    birth_date = models.DateField(default=date.today)
    image = models.ImageField(upload_to='images/', default='images/default.jpg')
    image_medium = ImageSpecField(source='image',
                                     processors=[ResizeToFill(250, 150)],
                                     format='JPEG',
                                     options={'quality': 60})
    image_small = ImageSpecField(source='image',
                                     processors=[ResizeToFill(100, 100)],
                                     format='JPEG',
                                     options={'quality': 60})
    body = models.TextField()
    passport_num = models.CharField(max_length=30, blank = True)
    #chip_num = models.CharField(max_length=30, blank = True)
    #chip_num = models.DecimalField(max_digits=20, decimal_places=0, blank = True)
    breeder = models. CharField(max_length=50, default='own breeding')


    class Meta:
            ordering = ['-birth_date',]

    class Harness(models.TextChoices):
        RED = 'RD', _('Red')
        BLUE = 'BL', _('Blue')
        SILVER = 'SL', _('Silver')
        GREEN = 'GR', _('Green')
        YELLOW = 'YL', _('Yellow')

    harness_size = models.CharField(
        max_length=2,
        choices=Harness.choices,
        default=Harness.SILVER,
    )


    def __unicode__(self):
        return self.harness_size

    def summary(self):
        return self.body[:800]
    def birth_date_pretty(self):
        return self.birth_date.strftime('%e %B %Y')
    def birth_date_year(self):
        return self.birth_date.strftime('%y')
    def is_neutered(self):
        return self.neutered.filter(status=1).count()

    def __str__(self):
        return self.name


class Medication(models.Model):
     name = models.CharField(max_length=100, help_text='i.e. Metacam (2 x 1 ml)')
     usage = models.CharField(max_length=200)

     def __str__(self):
        return self.name

class MedicalCard(models.Model):
     diagnosis = models.CharField(max_length=30)
     diagnosis_long = models.CharField(max_length=250, blank = True)
     treatment = models.ManyToManyField(Medication)
     dosage = models.CharField(max_length=100, blank = True)
     duration = models.DurationField(help_text='[DD] [[hh:]mm:]ss')
     dog = models.ForeignKey(Dog, on_delete=models.CASCADE)
     datalogger = models.ForeignKey(User, on_delete=models.CASCADE)
     active = models.BooleanField(default=True)
     time = models.DateTimeField(default=timezone.now)
     expired_date = models.DateTimeField(blank=True, null=True)
     notes = models.TextField(blank = True)


     def expire(self):
         now = timezone.now()
         if self.active == True and self.expired_date > now:
            return self.active.set(False)

     '''def active(self):
        now = timezone.now()
        if self.stanow and now < self.end:
            return True
        return False

     '''
     #vet_report = FileField(upload_to='documents/', max_length=100)

     class Meta:
             ordering = ['-time',]

     def __str__(self):
        return "%s %s" % (self.dog.name, self.diagnosis)
''' returns more than one value, dog gives error, add name from Dog class'''

class Person(models.Model):
     name = models.CharField(max_length=50)
     phone = models.CharField(max_length=50)
     email = models.EmailField(max_length = 254, blank=True)
     messenger = models.URLField(blank=True, help_text="m.me/username")
     PER_CHOICES = [('sponsor','Sponsor'), ('adopter','Adopter'), ('host','Host')]
     status = models.CharField(max_length=10, choices=PER_CHOICES)
     dog = models.ForeignKey(Dog, on_delete=models.CASCADE, blank=True)

     def __str__(self):
        return self.name

dog/forms.py
from django.forms import ModelForm
from .models import Dog


class DogForm(ModelForm):
     class Meta:
       model = Dog
       fields = '__all__'

       #fields.widget.attrs.update({'class': 'w3-button'})
       #body.widget.attrs.update(size='40')

dog/views.py
from django.shortcuts import render
from .models import Dog

# Create your views here.
from django.template.loader import get_template
from django.shortcuts import render, get_object_or_404, redirect
from .models import Dog, MedicalCard
from .forms import DogForm
from .filters import DogFilter


def alldogs(request):
    dogs = Dog.objects
    return render(request, 'dog/alldogs.html', {'dogs':dogs})

def dog_detail(request, dog_id):
    dogdetail = get_object_or_404(Dog, pk=dog_id)
    card_m = MedicalCard.objects.filter(dog_id=dog_id)
    context = {'dog':dogdetail, 'card_m':card_m}
    return render(request, 'dog/dog_detail.html', context)

def alldog_image(request):
    dogs = Dog.objects.all()
    myFilter = DogFilter(request.GET, queryset=dogs)
    dogs = myFilter.qs
    context = {'dogs':dogs, 'myFilter':myFilter}
    return render(request, 'dog/alldog_image.html', context)

def medicalcards(request):
    cards = MedicalCard.objects.filter(active=True)
    context = {'cards':cards}
    return render(request, 'dog/medicalcards.html', context)

def card_detail(request, medicalcard_id):
    carddetail = get_object_or_404(MedicalCard, pk=medicalcard_id),
    return render(request, 'dog/card_detail.html', {'carddetail':carddetail})

dog/templates/dog/alldog_image.html
{% extends './base.html' %}
{% load dog_count_tags %}
{% load widget_tweaks %}
{% block title %}Dogs{% endblock %}


{% block content %}
<button onclick="myFunction('Demo1')" class="w3-button w3-block w3-margin-bottom w3-theme-d1">Filter</button>
<div class="w3-conteiner w3-streath">

 <div id="Demo1" class="w3-container w3-hide">

			<form method="get">

				{{ myFilter.form }}

		    <button class="w3-button w3-white w3-border w3-border-red w3-round-large" type="submit">Search</button>
		  </form>

 </div>
</div>

 <!--XXX:
-->
  <div class="w3-contener w3-align-center">
		{% for dog in dogs %}
       <div class="w3-left">
			   <a href="{% url 'dog_detail' dog.id %}" style="text-decoration: none;">
         <img src="{{ dog.image_small.url }}" class="w3-image w3-hover-sepia"></a>
       </div>
  	{% endfor %}
  </div>

<script>
function myFunction(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>
{% endblock %}

dog/templates/dog/alldog_image1.html
{% extends './base.html' %}
{% load dog_count_tags %}
{% load widget_tweaks %}
{% block title %}Dogs{% endblock %}


{% block content %}

<div class="w3-small w3-padding-small w3-streath">
	<button onclick="myFunction('Demo1')" class="w3-button w3-block w3-gray w3-left-align">Open Filter</button>
 <div id="Demo1" class="w3-container w3-hide">

			<form method="get">

				{{ myFilter.form }}

		    <button class="w3-button w3-white w3-border w3-border-red w3-round-large" type="submit">Search</button>
		  </form>

 </div>
</div>
<br>
 <!--XXX:
-->
		{% for dog in dogs %}
       <div class="w3-left">
			   <a href="{% url 'dog_detail' dog.id %}" style="text-decoration: none;">
         <img src="{{ dog.image.url }}" class="w3-image" style="width:100px;height:100px;"></a>
       </div>
  	{% endfor %}

<script>
function myFunction(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>
{% endblock %}

dog/templates/dog/alldogs.html
		{% for dog in  dogs.all %}
        <div class="w3-half w3-container">
            <div class="w3-topbar w3-border-amber">
                <img src="{{ dog.image.url }}" alt="Kutyaszántúra" class="w3-image">

				<a href="{% url 'dog_detail' dog.id %}" style="text-decoration: none;">
                <h2>{{ dog.name }}</h2></a>
                {% if dog.leader %}
            <ul>
                <li>LEADER</li>
            </ul>
        {% else %}
            <p>Not leader</p>
        {% endif %}
                <h2>{{ dog.birth_date }}</h2>
                <h2>{{ dog.neutered }}</h2>
				<p class="w3-tiny">{{ dog.pub_date_pretty }}</p>
                <p>{{ dog.summary|safe }}</p>
			</div>
        </div>


	{% endfor %}

dog/templates/dog/base.html
{% load dog_count_tags %}
{% load widget_tweaks %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-teal.css">
<link rel="stylesheet" type="text/css" href="/SDDatabase/dog/templates/dog/w3.css" media="screen"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Modak">
<link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">

<style>
.w3-tangerine {
 font-family: 'Permanent Marker', serif;

}
</style>
</head>
<body>
<header class="w3-bar w3-theme-d4">

  <div class="w3-bar-item w3-left w3-mobile w3-xxlarge"><span class="w3-tangerine">Villmark</span><span class="w3-hide-small"> - Sled dog database</span></div>
  <div class="w3-bar-item w3-right w3-mobile w3-small w3-opacity w3-hide-small">Dogs in database: <span class="w3-xxlarge">{% dog_count %}</span></div>
  <a href="/admin/" class="w3-bar-item w3-right w3-button w3-round-large w3-mobile w3-hover-text-teal w3-xxlarge fa fa-gear"></a>
  <a href="/" class="w3-bar-item w3-right w3-button w3-round-large w3-mobile w3-hover-text-teal w3-xxlarge fa fa-id-card"></a>
  <a href="/medicalcards/" class="w3-bar-item w3-right w3-button w3-round-large w3-mobile w3-hover-text-teal w3-xxlarge fa fa-medkit"></a>
</header>

<div class="w3-container w3-margin-top">

{% block content %}
{% endblock %}

</div>
</body>
</html>

dog/templates/dog/card_detail.html
{% extends './base.html' %}
{% load widget_tweaks %}
{% block title %}Medical Card{% endblock %}


{% block content %}


   {% for c in carddetail %}

     <div class="w3-twothird">

         <table class="w3-table w3-striped w3-bordered">
         <thead class="w3-theme-d1"><tr><th style="width:30%">Medical Card - {{ c.dog }} - {{ c.id }}</th><th>Value: {{ c.diagnosis }}</th></tr></thead>
         <tbody>
         <tr><td style="width:30%">Position</td><td>{% if dog.leader %}LEADER{% else %}Not leader
         {% endif %}</td></tr>
         <tr><td style="width:30%">Diagnosis short:</td><td>{{ c.diagnosis}}</td></tr>
         <tr><td style="width:30%">Diagnosis long:</td><td>{{ c.diagnosis_long}}</td></tr>
         <tr><td style="width:30%">Treatment:</td><td>{% for medication in c.treatment.all %} {{ medication }} ({{ medication.usage }}),{% endfor %}</td></tr>
         <tr><td style="width:30%">dosage:</td><td>{{ c.dosage }}</td></tr>
         <tr><td style="width:30%">duration:</td><td>{{ c.duration }}</td></tr>
         <tr><td style="width:30%">created:</td><td>{{ c.time }}</td></tr>
         <tr><td style="width:30%">expire:</td><td>{{ c.expired_date}}</td></tr>
         <tr><td style="width:30%">datalogger:</td><td>{{ c.datalogger }}</td></tr>
         <tr><td style="width:30%">active:</td><td>{{ c.active }}</td></tr>
         <tr><td style="width:30%">notes:</td><td>{{ c.notes }}</td></tr>

         </tbody></table>
     </div>

   {% endfor %}

<script>
function myFunction(id) {
var x = document.getElementById(id);
if (x.className.indexOf("w3-show") == -1) {
x.className += " w3-show";
} else {
x.className = x.className.replace(" w3-show", "");
}
}
</script>
{% endblock %}

dog/templates/dog/dog_detail.html
{% extends './base.html' %}
{% block title %}{{ dog.name }} - details{% endblock %}
{% block content %}

<div class="w3-twothird">
  <img src="{{ dog.image.url }}" style="width:100%">
  <h1>{{ dog.name }}{% if dog.leader %}(L){% endif %}  '{{ dog.birth_date_year }}
    <span class="w3-medium">( Bjorn x Mandel )</span></h1>
  <table class="w3-table w3-striped w3-bordered">
  <thead class="w3-theme-d1"><tr><th style="width:30%">Dog</th><th>Value</th></tr></thead>
  <tbody>
  <tr><td style="width:30%">Position</td><td>{% if dog.leader %}LEADER{% else %}Not leader
  {% endif %}</td></tr>
  <tr><td>Location</td><td>{{ dog.get_location_display }}</td></tr>
  <tr><td style="width:30%">Adoption</td><td>{% if dog.avaible_for_adoption %}Avaible for adoption{% else %}Not avaible
  {% endif %}</td></tr>
  <tr><td>Sex</td><td>{{ dog.sex }} ({% if dog.neutered %}neutered{% else %}intact
  {% endif %})</td></tr>
  <tr><td style="width:30%">Sex status</td><td>{% if dog.neutered %}Neutered{% else %}Intact
  {% endif %}</td></tr>
  <tr><td>Date of birth</td><td>{{ dog.birth_date_pretty }}</td></tr>
  <tr><td>Harness size</td><td>{{ dog.get_harness_size_display }}</td></tr>
  <tr><td>Passport num.</td><td>{{ dog.passport_num }}</td></tr>
  <tr><td>Breeder</td><td>{{ dog.breeder }}</td></tr>
  <tr><td>Pedigree</td><td><a href="{{ dog.trekkhundreg }}">{{ dog.trekkhundreg }}</a></td></tr>
  </tbody></table>
  <br>
  </div>
  <div class="w3-third w3-padding">
  <h1>{{ dog.name }}</h1>
  <p>{{ dog.body }}</p>
  {% if user.is_authenticated %}
  <h4>Medical cards</h4>
  {% for b in card_m.all %}
  <p><a href="{% url 'card_detail' b.id %}" class="fa fa-medkit w3-hover-text-teal">
  Medical card - {{ b.id }}</a></p>
  {% endfor %}
  <h4>Uploaded files</h4>
  {% endif %}
</div>
{% endblock %}

dog/templates/dog/footer.html
{% load static %}
<!-- Footer -->
    <footer class="w3-contener w3-center w3-opacity">
      &copy;
            <script type="text/JavaScript">
                document.write(new Date().getFullYear());
           </script> Villmark
   </footer>

dog/templates/dog/medicalcards.html
{% extends './base.html' %}
{% block title %}Medical Cards{% endblock %}


{% block content %}

{% for card in cards %}
   <a href="{% url 'card_detail' card.id %}" style="text-decoration: none;">
   <div class="w3-left w3-card w3-hover-shadow w3-margin w3-padding">
    <h4>{{ card }}</h4>{{ card.time }}<hr>
    {% for medication in card.treatment.all %}<p><b>{{ medication }} {{ card.dosage }}</b></p>
    {% endfor %}
    @ {{ card.datalogger.first_name }}   {{ card.datalogger.last_name }}
   </div></a>
{% endfor %}

<script>
function myFunction(id) {
var x = document.getElementById(id);
if (x.className.indexOf("w3-show") == -1) {
x.className += " w3-show";
} else {
x.className = x.className.replace(" w3-show", "");
}
}
</script>
{% endblock %}